import { StyleSheet } from 'react-native';

export const appThemes = {
  light: {
    name: 'light',
    ink: '#111713',
    muted: '#667067',
    line: '#cfd8d1',
    surface: '#ffffff',
    canvas: '#eef4ef',
    hero: '#111713',
    heroText: '#f8fafc',
    heroMuted: '#c8d7ca',
    input: '#f7fbf8',
    blue: '#2f8f5b',
    green: '#2f8f5b',
    amber: '#b45309',
    red: '#b91c1c',
    infoBg: '#edf8f0',
    infoLine: '#b5dec1',
    infoText: '#14532d',
    fullBg: '#dff7e6',
    fullLine: '#9ed8ad',
    partialBg: '#fef3c7',
    partialLine: '#fcd34d',
    secondaryButton: '#eef8f1',
    secondaryLine: '#b5dec1',
    dangerButton: '#fff1f2',
    dangerLine: '#fecdd3',
  },
  dark: {
    name: 'dark',
    ink: '#E7F4FE',
    muted: '#8FCBFA',
    line: '#2198F4',
    surface: '#010E18',
    canvas: '#010E18',
    hero: '#010E18',
    heroText: '#ffffff',
    heroMuted: '#BBE0FC',
    input: '#032844',
    blue: '#2198F4',
    green: '#37A3F6',
    amber: '#8FCBFA',
    red: '#63B7F8',
    infoBg: '#032844',
    infoLine: '#37A3F6',
    infoText: '#E7F4FE',
    fullBg: '#032844',
    fullLine: '#2198F4',
    partialBg: '#054270',
    partialLine: '#37A3F6',
    secondaryButton: '#032844',
    secondaryLine: '#2198F4',
    dangerButton: '#032844',
    dangerLine: '#63B7F8',
  },
};

export function getAppStyles(themeMode = 'light') {
  const colors = appThemes[themeMode] ?? appThemes.light;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.canvas,
      padding: 20,
      paddingTop: 58,
    },
    loginHero: {
      backgroundColor: colors.hero,
      borderRadius: 20,
      padding: 24,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: colors.line,
    },
    brand: {
      color: colors.heroText,
      fontSize: 18,
      fontWeight: '800',
      marginBottom: 26,
    },
    brandSmall: {
      color: colors.blue,
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    heroTitle: {
      color: colors.heroText,
      fontSize: 32,
      fontWeight: '900',
      lineHeight: 38,
      marginBottom: 12,
    },
    heroCopy: {
      color: colors.heroMuted,
      fontSize: 16,
      lineHeight: 23,
    },
    heroCopyDark: {
      color: colors.heroMuted,
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 10,
    },
    authPanel: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.line,
    },
    panelTitle: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 4,
    },
    panelSubtitle: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 16,
    },
    dashboard: {
      flexGrow: 1,
      backgroundColor: colors.canvas,
      padding: 18,
      paddingTop: 58,
      paddingBottom: 30,
    },
    topBar: {
      gap: 14,
      marginBottom: 14,
    },
    homeTitleRow: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    homeTitleText: {
      flex: 1,
    },
    carIconButton: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
      minWidth: 44,
      paddingTop: 18,
    },
    homeLogout: {
      marginTop: 'auto',
      paddingTop: 18,
    },
    dashboardTitle: {
      color: colors.ink,
      fontSize: 30,
      fontWeight: '900',
      marginTop: 2,
    },
    heroPanel: {
      backgroundColor: colors.hero,
      borderRadius: 20,
      padding: 20,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: colors.line,
    },
    heroKicker: {
      color: colors.blue,
      fontSize: 13,
      fontWeight: '800',
      marginBottom: 8,
      textTransform: 'uppercase',
    },
    heroMetric: {
      color: colors.heroText,
      fontSize: 34,
      fontWeight: '900',
      marginBottom: 6,
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 18,
    },
    compactStatsGrid: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 12,
    },
    maintenanceSummaryPanel: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.line,
      marginBottom: 12,
      overflow: 'hidden',
    },
    maintenanceSummaryHeader: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.line,
    },
    maintenanceStatsGrid: {
      flexDirection: 'row',
    },
    maintenanceStatTile: {
      flex: 1,
      minHeight: 82,
      padding: 12,
      justifyContent: 'space-between',
      borderRightWidth: 1,
      borderRightColor: colors.line,
    },
    maintenanceStatTileLast: {
      borderRightWidth: 0,
    },
    statTile: {
      width: '48%',
      minHeight: 92,
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
      justifyContent: 'space-between',
    },
    statLabel: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '700',
    },
    statValue: {
      color: colors.ink,
      fontSize: 26,
      fontWeight: '900',
    },
    compactStatTile: {
      flex: 1,
      minHeight: 82,
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.line,
      justifyContent: 'space-between',
    },
    compactStatValue: {
      color: colors.ink,
      fontSize: 18,
      fontWeight: '900',
    },
    statMeta: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    homeActionGrid: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 18,
    },
    homeActionButton: {
      flex: 1,
      minHeight: 76,
      backgroundColor: colors.surface,
      borderRadius: 18,
      paddingHorizontal: 8,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: colors.line,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
    },
    homeActionText: {
      color: colors.ink,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'center',
    },
    sectionHeader: {
      marginTop: 10,
      marginBottom: 10,
    },
    sectionEyebrow: {
      color: colors.blue,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    sectionHeading: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
    },
    taskRow: {
      gap: 10,
      marginBottom: 4,
    },
    taskItem: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.line,
    },
    taskTitle: {
      color: colors.ink,
      fontSize: 17,
      fontWeight: '900',
      marginBottom: 4,
    },
    taskMeta: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
    },
    carOption: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.line,
      flexDirection: 'row',
      gap: 12,
      minHeight: 78,
      padding: 14,
    },
    carOptionSelected: {
      backgroundColor: colors.input,
      borderColor: colors.green,
    },
    carOptionText: {
      flex: 1,
    },
    carSelectedText: {
      color: colors.green,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    actionGrid: {
      gap: 12,
      marginBottom: 14,
    },
    analyticsActionGrid: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 6,
    },
    analyticsActionButton: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      flex: 1,
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      minHeight: 46,
      paddingHorizontal: 10,
    },
    analyticsActionText: {
      color: colors.ink,
      fontSize: 13,
      fontWeight: '900',
      textAlign: 'center',
    },
    actionCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.line,
      minHeight: 132,
      padding: 18,
      justifyContent: 'space-between',
    },
    actionEyebrow: {
      color: colors.green,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
      marginBottom: 8,
    },
    actionTitle: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 8,
    },
    actionDescription: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
    },
    formScreen: {
      flexGrow: 1,
      backgroundColor: colors.canvas,
      padding: 18,
      paddingTop: 58,
      paddingBottom: 30,
    },
    formHeader: {
      marginBottom: 14,
    },
    formPanel: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.line,
    },
    userHeader: {
      paddingVertical: 2,
    },
    userLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    userText: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: '900',
      marginBottom: 8,
    },
    logoutText: {
      color: colors.blue,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'center',
    },
    sectionTitle: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: '900',
      marginBottom: 10,
      marginTop: 6,
    },
    input: {
      backgroundColor: colors.input,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      color: colors.ink,
      fontSize: 16,
      minHeight: 52,
      marginBottom: 12,
      paddingHorizontal: 14,
    },
    datePickerButton: {
      alignItems: 'center',
      backgroundColor: colors.input,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 58,
      marginBottom: 12,
      paddingHorizontal: 14,
    },
    datePickerText: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: '900',
      marginTop: 3,
    },
    datePickerPanel: {
      backgroundColor: colors.input,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      marginBottom: 12,
      overflow: 'hidden',
    },
    datePickerDoneButton: {
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: colors.line,
      minHeight: 44,
      justifyContent: 'center',
    },
    datePickerDoneText: {
      color: colors.blue,
      fontSize: 15,
      fontWeight: '900',
    },
    checkboxRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      minHeight: 48,
      marginBottom: 4,
    },
    checkboxBox: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: colors.line,
      height: 26,
      justifyContent: 'center',
      width: 26,
    },
    checkboxText: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: '900',
    },
    conditionalPanel: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      marginBottom: 10,
      marginTop: 6,
      padding: 12,
    },
    filterTypeRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 12,
    },
    filterTypeButton: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: colors.input,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.line,
      minHeight: 46,
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
    filterTypeButtonSelected: {
      backgroundColor: colors.blue,
      borderColor: colors.green,
    },
    filterTypeText: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: '900',
    },
    filterTypeTextSelected: {
      color: themeMode === 'dark' ? '#010E18' : '#ffffff',
    },
    button: {
      backgroundColor: colors.blue,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.green,
      minHeight: 52,
      justifyContent: 'center',
      marginTop: 10,
      paddingHorizontal: 16,
    },
    buttonText: {
      color: themeMode === 'dark' ? '#010E18' : '#ffffff',
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'center',
    },
    secondaryButton: {
      backgroundColor: colors.secondaryButton,
      borderRadius: 16,
      minHeight: 52,
      justifyContent: 'center',
      marginTop: 10,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.secondaryLine,
    },
    secondaryButtonText: {
      color: colors.blue,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'center',
    },
    dangerButton: {
      backgroundColor: colors.dangerButton,
      borderRadius: 16,
      minHeight: 48,
      justifyContent: 'center',
      marginTop: 10,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.dangerLine,
    },
    dangerButtonText: {
      color: colors.red,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    backButton: {
      minHeight: 48,
      justifyContent: 'center',
      marginTop: 8,
    },
    backButtonText: {
      color: colors.blue,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'center',
    },
    optionButton: {
      backgroundColor: colors.input,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      minHeight: 50,
      justifyContent: 'center',
      marginBottom: 10,
      paddingHorizontal: 14,
    },
    optionSelectedFull: {
      backgroundColor: '#075C9C',
      borderColor: colors.fullLine,
      borderWidth: 2,
    },
    optionSelectedPartial: {
      backgroundColor: '#054270',
      borderColor: colors.partialLine,
      borderWidth: 2,
    },
    optionText: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    optionTextSelected: {
      color: '#ffffff',
    },
    infoBox: {
      backgroundColor: colors.infoBg,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.infoLine,
      padding: 13,
      marginTop: 4,
      marginBottom: 8,
    },
    infoText: {
      color: colors.infoText,
      fontSize: 14,
      lineHeight: 20,
    },
    historyContainer: {
      marginTop: 20,
    },
    historyTitle: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 10,
    },
    emptyText: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.line,
      color: colors.muted,
      fontSize: 15,
      padding: 18,
      textAlign: 'center',
    },
    historyCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 16,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.line,
    },
    historyCardHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    historyMain: {
      color: colors.ink,
      fontSize: 17,
      fontWeight: '900',
    },
    historyBadge: {
      borderRadius: 14,
      fontSize: 12,
      fontWeight: '900',
      overflow: 'hidden',
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    historyBadgeFull: {
      backgroundColor: colors.fullBg,
      color: colors.green,
    },
    historyBadgePartial: {
      backgroundColor: colors.partialBg,
      color: colors.amber,
    },
    historyText: {
      color: colors.muted,
      fontSize: 14,
      marginBottom: 4,
    },
    consumoText: {
      color: colors.green,
      fontSize: 15,
      fontWeight: '900',
      marginTop: 8,
    },
    noConsumoText: {
      color: colors.amber,
      fontSize: 14,
      fontWeight: '700',
      marginTop: 8,
    },
  });
}

export const styles = getAppStyles('light');
