import { StyleSheet } from 'react-native';

export const appThemes = {
  light: {
    name: 'light',
    ink: '#111713',
    muted: '#667067',
    line: '#cfd8d1',
    surface: '#ffffff',
    canvas: '#eef4ef',
    hero: '#111713',
    heroText: '#f8fafc',
    heroMuted: '#c8d7ca',
    input: '#f7fbf8',
    blue: '#2f8f5b',
    green: '#2f8f5b',
    amber: '#b45309',
    red: '#b91c1c',
    infoBg: '#edf8f0',
    infoLine: '#b5dec1',
    infoText: '#14532d',
    fullBg: '#dff7e6',
    fullLine: '#9ed8ad',
    partialBg: '#fef3c7',
    partialLine: '#fcd34d',
    secondaryButton: '#eef8f1',
    secondaryLine: '#b5dec1',
    dangerButton: '#fff1f2',
    dangerLine: '#fecdd3',
  },
  dark: {
    name: 'dark',
    ink: '#eefbf0',
    muted: '#8fa995',
    line: '#244332',
    surface: '#0f1511',
    canvas: '#030604',
    hero: '#07100b',
    heroText: '#ffffff',
    heroMuted: '#a7c8ae',
    input: '#09100c',
    blue: '#6ee789',
    green: '#6ee789',
    amber: '#fbbf24',
    red: '#fb7185',
    infoBg: '#0b1c12',
    infoLine: '#1f6f3d',
    infoText: '#b7f8c5',
    fullBg: '#0d2415',
    fullLine: '#2f8f5b',
    partialBg: '#281f0a',
    partialLine: '#92400e',
    secondaryButton: '#0b1c12',
    secondaryLine: '#244332',
    dangerButton: '#35151d',
    dangerLine: '#7f1d1d',
  },
};

export function getAppStyles(themeMode = 'light') {
  const colors = appThemes[themeMode] ?? appThemes.light;

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.canvas,
      padding: 20,
    },
    loginHero: {
      backgroundColor: colors.hero,
      borderRadius: 8,
      padding: 24,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: colors.line,
    },
    brand: {
      color: colors.heroText,
      fontSize: 18,
      fontWeight: '800',
      marginBottom: 26,
    },
    brandSmall: {
      color: colors.blue,
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    heroTitle: {
      color: colors.heroText,
      fontSize: 32,
      fontWeight: '900',
      lineHeight: 38,
      marginBottom: 12,
    },
    heroCopy: {
      color: colors.heroMuted,
      fontSize: 16,
      lineHeight: 23,
    },
    heroCopyDark: {
      color: colors.heroMuted,
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 10,
    },
    authPanel: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.line,
    },
    panelTitle: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 4,
    },
    panelSubtitle: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 16,
    },
    dashboard: {
      flexGrow: 1,
      backgroundColor: colors.canvas,
      padding: 18,
      paddingBottom: 30,
    },
    topBar: {
      gap: 14,
      marginBottom: 14,
    },
    dashboardTitle: {
      color: colors.ink,
      fontSize: 30,
      fontWeight: '900',
      marginTop: 2,
    },
    heroPanel: {
      backgroundColor: colors.hero,
      borderRadius: 8,
      padding: 20,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: colors.line,
    },
    heroKicker: {
      color: colors.blue,
      fontSize: 13,
      fontWeight: '800',
      marginBottom: 8,
      textTransform: 'uppercase',
    },
    heroMetric: {
      color: colors.heroText,
      fontSize: 34,
      fontWeight: '900',
      marginBottom: 6,
    },
    themeToggle: {
      alignSelf: 'flex-start',
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.line,
      flexDirection: 'row',
      gap: 8,
      minHeight: 42,
      alignItems: 'center',
      paddingHorizontal: 12,
      marginTop: 12,
    },
    themeToggleText: {
      color: colors.ink,
      fontSize: 14,
      fontWeight: '900',
    },
    themeToggleMeta: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 18,
    },
    statTile: {
      width: '48%',
      minHeight: 92,
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
      justifyContent: 'space-between',
    },
    statLabel: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '700',
    },
    statValue: {
      color: colors.ink,
      fontSize: 26,
      fontWeight: '900',
    },
    sectionHeader: {
      marginBottom: 10,
    },
    sectionEyebrow: {
      color: colors.blue,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    sectionHeading: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
    },
    taskRow: {
      gap: 10,
      marginBottom: 4,
    },
    taskItem: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.line,
    },
    taskTitle: {
      color: colors.ink,
      fontSize: 17,
      fontWeight: '900',
      marginBottom: 4,
    },
    taskMeta: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
    },
    actionGrid: {
      gap: 12,
      marginBottom: 14,
    },
    actionCard: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.line,
      minHeight: 132,
      padding: 18,
      justifyContent: 'space-between',
    },
    actionEyebrow: {
      color: colors.green,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
      marginBottom: 8,
    },
    actionTitle: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 8,
    },
    actionDescription: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
    },
    formScreen: {
      flexGrow: 1,
      backgroundColor: colors.canvas,
      padding: 18,
      paddingBottom: 30,
    },
    formHeader: {
      marginBottom: 14,
    },
    formPanel: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.line,
    },
    userBox: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.line,
    },
    userLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    userText: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: '900',
      marginBottom: 8,
    },
    logoutText: {
      color: colors.red,
      fontSize: 14,
      fontWeight: '800',
    },
    sectionTitle: {
      color: colors.ink,
      fontSize: 16,
      fontWeight: '900',
      marginBottom: 10,
      marginTop: 6,
    },
    input: {
      backgroundColor: colors.input,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.line,
      color: colors.ink,
      fontSize: 16,
      minHeight: 52,
      marginBottom: 12,
      paddingHorizontal: 14,
    },
    button: {
      backgroundColor: colors.blue,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.green,
      minHeight: 52,
      justifyContent: 'center',
      marginTop: 10,
      paddingHorizontal: 16,
    },
    buttonText: {
      color: themeMode === 'dark' ? '#031007' : '#ffffff',
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'center',
    },
    secondaryButton: {
      backgroundColor: colors.secondaryButton,
      borderRadius: 8,
      minHeight: 52,
      justifyContent: 'center',
      marginTop: 10,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.secondaryLine,
    },
    secondaryButtonText: {
      color: colors.blue,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'center',
    },
    dangerButton: {
      backgroundColor: colors.dangerButton,
      borderRadius: 8,
      minHeight: 48,
      justifyContent: 'center',
      marginTop: 10,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.dangerLine,
    },
    dangerButtonText: {
      color: colors.red,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    backButton: {
      minHeight: 48,
      justifyContent: 'center',
      marginTop: 8,
    },
    backButtonText: {
      color: colors.blue,
      fontSize: 16,
      fontWeight: '900',
      textAlign: 'center',
    },
    optionButton: {
      backgroundColor: colors.input,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.line,
      minHeight: 50,
      justifyContent: 'center',
      marginBottom: 10,
      paddingHorizontal: 14,
    },
    optionSelectedFull: {
      backgroundColor: colors.fullBg,
      borderColor: colors.fullLine,
    },
    optionSelectedPartial: {
      backgroundColor: colors.partialBg,
      borderColor: colors.partialLine,
    },
    optionText: {
      color: colors.ink,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
    },
    optionTextSelected: {
      color: colors.ink,
    },
    infoBox: {
      backgroundColor: colors.infoBg,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.infoLine,
      padding: 13,
      marginTop: 4,
      marginBottom: 8,
    },
    infoText: {
      color: colors.infoText,
      fontSize: 14,
      lineHeight: 20,
    },
    historyContainer: {
      marginTop: 20,
    },
    historyTitle: {
      color: colors.ink,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 10,
    },
    emptyText: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.line,
      color: colors.muted,
      fontSize: 15,
      padding: 18,
      textAlign: 'center',
    },
    historyCard: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 16,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.line,
    },
    historyCardHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    historyMain: {
      color: colors.ink,
      fontSize: 17,
      fontWeight: '900',
    },
    historyBadge: {
      borderRadius: 8,
      fontSize: 12,
      fontWeight: '900',
      overflow: 'hidden',
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    historyBadgeFull: {
      backgroundColor: colors.fullBg,
      color: colors.green,
    },
    historyBadgePartial: {
      backgroundColor: colors.partialBg,
      color: colors.amber,
    },
    historyText: {
      color: colors.muted,
      fontSize: 14,
      marginBottom: 4,
    },
    consumoText: {
      color: colors.green,
      fontSize: 15,
      fontWeight: '900',
      marginTop: 8,
    },
    noConsumoText: {
      color: colors.amber,
      fontSize: 14,
      fontWeight: '700',
      marginTop: 8,
    },
  });
}

export const styles = getAppStyles('light');
